name: Deploy
on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: export NODE_ENV=development
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: deploy file to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: out
          remote: /var/www/blessing-dapp
          host: ${{ secrets.SERVER_IP }}
          username: root
          password: ${{ secrets.SERVER_PASS }}
